### ISSUE TITLE
Splitting VAO/VBO creation

### ISSUE THREAD

**Issue by hussein-aitlahcen** [hussein-aitlahcen/purespace#3]
Splitting the VAO creation from the VBO creation would allow us to create a single VBO containing  the vertices of all sprites. We could then create one VAO for each sprite containing the according offset in the VBO (offset0 + spriteIndex * nbComponents).
Instead of having `sprite * (VAO + VBO)` we would have `sprite * VAO + VBO`
The benefit will come from the GPU not having to switch the VBO.

**Comment by hussein-aitlahcen** [comment]
@Raveline is that better ?

**Comment by Raveline** [comment]
That's impressive ! It could be refined even more so by using an Element Buffer Object, and an indices list to reduce the number of vertices you have to define for the rectangle (basically just giving the 4 vertices of the rectangles, and using DrawElement), but that's really a small improvement - more useful for huge meshes. (But it might be good to remember this if we need more perfs later on).

**Comment by hussein-aitlahcen** [comment]
Oh yeah, didn't went to that level in OpenGL's documentation ^^ !
Could you approve please :) ?
